# Generated by Django 5.0.1 on 2024-01-08 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapps', '0007_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalapps.company'),
        ),
    ]
